columns:
  - ArticleId: int
  - Text: category
  - Category: category

numerical_columns:
  - ArticleId

categorical_columns:
  - Text
  - Category

drop_columns:
  - case_id
  - yr_of_estab

# for data transformation
num_features:
  - no_of_employees
  - prevailing_wage
  - company_age

or_columns:
  - has_job_experience
  - requires_job_training
  - full_time_position
  - education_of_employee

oh_columns:
  - continent
  - unit_of_wage
  - region_of_employment

transform_columns:
  - no_of_employees
  - company_age